SELECT [athena_to_s3_scholar_data.csv].[appnum] AS "Conf",
	[athena_to_s3_scholar_data.csv].[childid],
	[athena_to_s3_scholar_data.csv].[familyid],
	[athena_to_s3_scholar_data.csv].[familynum],
	[athena_to_s3_responsible_adults.csv].[responsibleadultid],
	[athena_to_s3_scholar_data.csv].[firstname] AS "child first name",
	[athena_to_s3_scholar_data.csv].[lastname] AS "child last name",
	[enrolledschoolname],
	[appdate],
	[applicationstatus],
	[bestcurrentstatus],
	[bestpullstatus],
	[gradeabbrev] AS "entering grade",
	[acceptedschoolcode],
	[acceptedschooladminadded],
	[acceptedschoolrank],
	[currentaccepteddate],
	[firstacceptdate],
	[highestrankschoolname],
	[applyingtoschoolany],
	[appclosedate],
	[closerequest],
	[closerequestdate],
	[importedscholarid],
	[isapplying],
	[isreopened],
	[reopendate],
	[source],
	[uberapplicationlate],
	[athena_to_s3_responsible_adults.csv].[firstname] AS "parent first name",
	[athena_to_s3_responsible_adults.csv].[lastname] AS "parent last name",
	[athena_to_s3_responsible_adults.csv].[email],
	[athena_to_s3_responsible_adults.csv].[cellphone],
	[athena_to_s3_responsible_adults.csv].[homephone],
	[athena_to_s3_responsible_adults.csv].[workphone],
	[athena_to_s3_responsible_adults.csv].[workext],
	[athena_to_s3_responsible_adults.csv].[rfscompleted], 
	[athena_to_s3_responsible_adults.csv].[rfswatched],
	[athena_to_s3_responsible_adults.csv].[rfsinvited],
	[athena_to_s3_customfields_data.csv].[uniform fitting invited],
	[athena_to_s3_customfields_data.csv].[uniform fitting attended],
	[athena_to_s3_customfields_data.csv].[registration invited],
	[athena_to_s3_customfields_data.csv].[registration attended],
	[athena_to_s3_customfields_data.csv].[dress rehearsal invited],
	[athena_to_s3_customfields_data.csv].[dress rehearsal attended],
	[athena_to_s3_customfields_data.csv].[birth certificate],
	[athena_to_s3_customfields_data.csv].[health form],
	[athena_to_s3_customfields_data.csv].[immunization record],
	[athena_to_s3_customfields_data.csv].[proof of residency], 
	[athena_to_s3_responsible_adults.csv].[language],
	[athena_to_s3_customfields_data.csv].[accept_seat_and_decline_wl],
	[athena_to_s3_customfields_data.csv].[accepted_but_wl_open],
	[athena_to_s3_customfields_data.csv].[close request survey],
	[athena_to_s3_customfields_data.csv].[reopen request status],
	[athena_to_s3_customfields_data.csv].[reopen request date],
FROM [CSV1].[athena_to_s3_scholar_data.csv]
LEFT JOIN [CSV1].[athena_to_s3_responsible_adults.csv] ON [CSV1].[athena_to_s3_scholar_data.csv].responsibleadultid = [CSV1].[athena_to_s3_responsible_adults.csv].responsibleadultid 
LEFT JOIN [CSV1].[athena_to_s3_customfields_data.csv] ON [CSV1].[athena_to_s3_scholar_data.csv].childid = [CSV1].[athena_to_s3_customfields_data.csv].childid 
LEFT JOIN [CSV1].[athena_to_s3_family_members.csv] ON [CSV1].[athena_to_s3_scholar_data.csv].responsibleadultid = [CSV1].[athena_to_s3_family_members.csv].responsibleadultid
ORDER BY [athena_to_s3_scholar_data.csv].appdate DESC;



Applying to School (Rank)