SELECT
	LEFT([athena_to_s3_scholar_data.csv].appdate, 10) AS "appdate", 
	[athena_to_s3_scholar_data.csv].appnum AS "Conf Number", 
	[athena_to_s3_scholar_data.csv].applicationstatus, 
	[athena_to_s3_scholar_data.csv].gradeabbrev, 
	[athena_to_s3_scholar_data.csv].highestrankschoolname, 
	[athena_to_s3_scholar_data.csv].applyingtoschoolany, 
	[athena_to_s3_scholar_data.csv].utm_source, 
	[athena_to_s3_scholar_data.csv].utm_campaign, 
	[athena_to_s3_scholar_data.csv].utm_term, 
	[athena_to_s3_scholar_data.csv].utm_medium, 
	[athena_to_s3_scholar_data.csv].utm_content, 
	[athena_to_s3_scholar_data.csv].source, 
	[athena_to_s3_responsible_adults.csv].street, 
	[athena_to_s3_responsible_adults.csv].city, 
	[athena_to_s3_responsible_adults.csv].borough, 
	[athena_to_s3_responsible_adults.csv].state, 
	LEFT([athena_to_s3_responsible_adults.csv].zip, 5) AS "zip", 
	[athena_to_s3_responsible_adults.csv].schooldistrict, 
	[athena_to_s3_scholar_data.csv].acceptedschoolcode, 
	[athena_to_s3_scholar_data.csv].currentschool, 
	[athena_to_s3_scholar_data.csv].isell AS "ELL grade 1-4", 
	[athena_to_s3_scholar_data.csv].homespeakell AS "ELL grade K", 
	[athena_to_s3_responsible_adults.csv].responsibleadultid, 
	[athena_to_s3_responsible_adults.csv].firstname AS "parent first name", 
	[athena_to_s3_responsible_adults.csv].lastname AS "parent last name", 
	[athena_to_s3_responsible_adults.csv].email AS "parent email", 
	[athena_to_s3_responsible_adults.csv].cellphone AS "parent cell phone", 
	[athena_to_s3_scholar_data.csv].heardaboutindex, 
	[athena_to_s3_scholar_data.csv].referralsource, 
FROM [CSV1].[athena_to_s3_scholar_data.csv] 
LEFT JOIN [CSV1].[athena_to_s3_responsible_adults.csv] 
ON [CSV1].[athena_to_s3_scholar_data.csv].responsibleadultid = [CSV1].[athena_to_s3_responsible_adults.csv].responsibleadultid 
ORDER BY [athena_to_s3_scholar_data.csv].appdate DESC;